=== Tatarana/thac0berry-data/schemas/mundane-item.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://thac0berry/schemas/mundane-item.schema.json",
  "title": "Itens comuns",
  "description": "Espelha o decode em Swift: Models/MundaneItem.swift.",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "name",
      "category"
    ],
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "category": {
        "type": "string"
      },
      "cost": {
        "type": [
          "string",
          "null"
        ]
      },
      "weight": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  }
}

=== Tatarana/thac0berry-data/data/mundane_items.json
[{"id":"backpack","name":"Backpack","category":"Miscellaneous Equipment","cost":"2 gp","weight":"2 lbs."},{"id":"barrel_small","name":"Barrel, small","category":"Miscellaneous Equipment","cost":"2 gp","weight":"30 lbs."},{"id":"basket_large","name":"Basket, Large","category":"Miscellaneous Equipment","cost":"3 sp","weight":"1 lbs."},{"id":"basket_small","name":"Basket, Small","category":"Miscellaneous Equipment","cost":"5 cp","weight":"*"},{"id":"bell","name":"Bell","category":"Miscellaneous Equipment","cost":"1 gp","weight":null},{"id":"belt_pouch_large","name":"Belt pouch, Large","category":"Miscellaneous Equipment","cost":"1 gp","weight":"1 lbs."},{"id":"belt_pouch_small","name":"Belt pouch, Small","category":"Miscellaneous Equipment","cost":"7 sp","weight":"1/2 lbs."},{"id":"block_and_tackle","name":"Block and tackle","category":"Miscellaneous Equipment","cost":"5 gp","weight":"5 lbs."},{"id":"bolt_case","name":"Bolt case","category":"Miscellaneous Equipment","cost":"1 gp","weight":"1 lbs."},{"id":"bucket","name":"Bucket","category":"Miscellaneous Equipment","cost":"5 sp","weight":"3 lbs."},{"id":"chain_per_ft_heavy","name":"Chain (per ft.), Heavy","category":"Miscellaneous Equipment","cost":"4 gp","weight":"3 lbs."},{"id":"chain_per_ft_light","name":"Chain (per ft.), Light","category":"Miscellaneous Equipment","cost":"3 gp","weight":"1 lbs."},{"id":"chest_large","name":"Chest, Large","category":"Miscellaneous Equipment","cost":"2 gp","weight":"25 lbs."},{"id":"chest_small","name":"Chest, Small","category":"Miscellaneous Equipment","cost":"1 gp","weight":"10 lbs."},{"id":"cloth_per_10_sq_yds_common","name":"Cloth (per 10 sq. yds.), Common","category":"Miscellaneous Equipment","cost":"7 gp","weight":"10 lbs."},{"id":"cloth_per_10_sq_yds_fine","name":"Cloth (per 10 sq. yds.), Fine","category":"Miscellaneous Equipment","cost":"50 gp","weight":"10 lbs."},{"id":"cloth_per_10_sq_yds_rich","name":"Cloth (per 10 sq. yds.), Rich","category":"Miscellaneous Equipment","cost":"100 gp","weight":"10 lbs."},{"id":"candle","name":"Candle","category":"Miscellaneous Equipment","cost":"1 cp","weight":"*"},{"id":"canvas_per_sq_yard","name":"Canvas (per sq. yard)","category":"Miscellaneous Equipment","cost":"4 sp","weight":"1 lbs."},{"id":"chalk","name":"Chalk","category":"Miscellaneous Equipment","cost":"1 cp","weight":"*"},{"id":"crampons","name":"Crampons","category":"Miscellaneous Equipment","cost":"4 gp","weight":"2 lbs."},{"id":"fishhook","name":"Fishhook","category":"Miscellaneous Equipment","cost":"1 sp","weight":"**"},{"id":"fishing_net_10_ft_sq","name":"Fishing net, 10 ft. sq.","category":"Miscellaneous Equipment","cost":"4 gp","weight":"5 lbs."},{"id":"flint_and_steel","name":"Flint and steel","category":"Miscellaneous Equipment","cost":"5 sp","weight":"*"},{"id":"glass_bottle","name":"Glass bottle","category":"Miscellaneous Equipment","cost":"10 gp","weight":"*"},{"id":"grappling_hook","name":"Grappling hook","category":"Miscellaneous Equipment","cost":"8 sp","weight":"4 lbs."},{"id":"holy_item_symbol_water_etc","name":"Holy item (symbol, water, etc.)","category":"Miscellaneous Equipment","cost":"25 gp","weight":"*"},{"id":"hourglass","name":"Hourglass","category":"Miscellaneous Equipment","cost":"25 gp","weight":"1 lbs."},{"id":"iron_pot","name":"Iron pot","category":"Miscellaneous Equipment","cost":"5 sp","weight":"2 lbs."},{"id":"ladder_10_ft","name":"Ladder, 10 ft.","category":"Miscellaneous Equipment","cost":"5 cp","weight":"20 lbs."},{"id":"lantern_beacon","name":"Lantern, Beacon","category":"Miscellaneous Equipment","cost":"150 gp","weight":"50 lbs."},{"id":"lantern_bullseye","name":"Lantern, Bullseye","category":"Miscellaneous Equipment","cost":"12 gp","weight":"3 lbs."},{"id":"lantern_hooded","name":"Lantern, Hooded","category":"Miscellaneous Equipment","cost":"7 gp","weight":"2 lbs."},{"id":"lock_good","name":"Lock, Good","category":"Miscellaneous Equipment","cost":"100 gp","weight":"1 lbs."},{"id":"lock_poor","name":"Lock, Poor","category":"Miscellaneous Equipment","cost":"20 gp","weight":"1 lbs."},{"id":"magnifying_glass","name":"Magnifying glass","category":"Miscellaneous Equipment","cost":"100 gp","weight":"*"},{"id":"map_or_scroll_case","name":"Map or scroll case","category":"Miscellaneous Equipment","cost":"8 sp","weight":"1/2 lbs."},{"id":"merchant_s_scale","name":"Merchant's scale","category":"Miscellaneous Equipment","cost":"2 gp","weight":"1 lbs."},{"id":"mirror_small_metal","name":"Mirror, small metal","category":"Miscellaneous Equipment","cost":"10 gp","weight":"*"},{"id":"musical_instrument","name":"Musical instrument","category":"Miscellaneous Equipment","cost":"5-100 gp","weight":"1/2-3 lbs."},{"id":"oil_per_flask_greek_fire","name":"Oil (per flask), Greek fire","category":"Miscellaneous Equipment","cost":"10 gp","weight":"2 lbs."},{"id":"oil_per_flask_lamp","name":"Oil (per flask), Lamp","category":"Miscellaneous Equipment","cost":"6 cp","weight":"1 lbs."},{"id":"paper_per_sheet","name":"Paper (per sheet)","category":"Miscellaneous Equipment","cost":"2 gp","weight":"**"},{"id":"papyrus_per_sheet","name":"Papyrus (per sheet)","category":"Miscellaneous Equipment","cost":"8 sp","weight":"**"},{"id":"parchment_per_sheet","name":"Parchment (per sheet)","category":"Miscellaneous Equipment","cost":"1 gp","weight":"**"},{"id":"perfume_per_vial","name":"Perfume (per vial)","category":"Miscellaneous Equipment","cost":"5 gp","weight":"*"},{"id":"piton","name":"Piton","category":"Miscellaneous Equipment","cost":"3 cp","weight":"1/2 lbs."},{"id":"quiver","name":"Quiver","category":"Miscellaneous Equipment","cost":"8 sp","weight":"1 lbs."},{"id":"rope_per_50_ft_hemp","name":"Rope (per 50 ft.), Hemp","category":"Miscellaneous Equipment","cost":"1 gp","weight":"20 lbs."},{"id":"rope_per_50_ft_silk","name":"Rope (per 50 ft.), Silk","category":"Miscellaneous Equipment","cost":"10 gp","weight":"8 lbs."},{"id":"sack_large","name":"Sack, Large","category":"Miscellaneous Equipment","cost":"2 sp","weight":"1/2 lbs."},{"id":"sack_small","name":"Sack, Small","category":"Miscellaneous Equipment","cost":"5 cp","weight":"*"},{"id":"sealing_candle_wax_per_lb","name":"Sealing/candle wax (per lb.)","category":"Miscellaneous Equipment","cost":"1 gp","weight":"1 lbs."},{"id":"sewing_needle","name":"Sewing needle","category":"Miscellaneous Equipment","cost":"5 sp*","weight":"*"},{"id":"signal_whistle","name":"Signal whistle","category":"Miscellaneous Equipment","cost":"8 sp","weight":"*"},{"id":"signet_ring_or_personal_seal","name":"Signet ring or personal seal","category":"Miscellaneous Equipment","cost":"5 gp","weight":"*"},{"id":"soap_per_lb","name":"Soap (per lb.)","category":"Miscellaneous Equipment","cost":"5 sp","weight":"1 lbs."},{"id":"spyglass","name":"Spyglass","category":"Miscellaneous Equipment","cost":"1,000 gp","weight":"1 lbs."},{"id":"tent_large","name":"Tent, Large","category":"Miscellaneous Equipment","cost":"25 gp","weight":"20 lbs."},{"id":"tent_pavilion","name":"Tent, Pavilion","category":"Miscellaneous Equipment","cost":"100 gp","weight":"50 lbs."},{"id":"tent_small","name":"Tent, Small","category":"Miscellaneous Equipment","cost":"5 gp","weight":"10 lbs."},{"id":"thieves_picks","name":"Thieves' picks","category":"Miscellaneous Equipment","cost":"30 gp","weight":"1 lbs."},{"id":"torch","name":"Torch","category":"Miscellaneous Equipment","cost":"1 cp","weight":"1 lbs."},{"id":"water_clock","name":"Water clock","category":"Miscellaneous Equipment","cost":"1,000 gp","weight":"200 lbs."},{"id":"whetstone","name":"Whetstone","category":"Miscellaneous Equipment","cost":"2 cp","weight":"1 lbs."},{"id":"wineskin","name":"Wineskin","category":"Miscellaneous Equipment","cost":"8 sp","weight":"1 lbs."},{"id":"winter_blanket","name":"Winter blanket","category":"Miscellaneous Equipment","cost":"5 sp","weight":"3 lbs."},{"id":"writing_ink_per_vial","name":"Writing ink (per vial)","category":"Miscellaneous Equipment","cost":"8 gp","weight":"*"},{"id":"belt","name":"Belt","category":"Clothing","cost":"3 sp","weight":null},{"id":"boots_riding","name":"Boots, Riding","category":"Clothing","cost":"3 gp","weight":null},{"id":"boots_soft","name":"Boots, Soft","category":"Clothing","cost":"1 gp","weight":null},{"id":"breeches","name":"Breeches","category":"Clothing","cost":"2 gp","weight":null},{"id":"cap_hat","name":"Cap, hat","category":"Clothing","cost":"1 sp","weight":null},{"id":"cloak_good_cloth","name":"Cloak, Good cloth","category":"Clothing","cost":"8 sp","weight":null},{"id":"cloak_fine_fur","name":"Cloak, Fine fur","category":"Clothing","cost":"50 gp","weight":null},{"id":"girdle","name":"Girdle","category":"Clothing","cost":"3 gp","weight":null},{"id":"gloves","name":"Gloves","category":"Clothing","cost":"1 gp","weight":null},{"id":"gown_common","name":"Gown, common","category":"Clothing","cost":"12 sp","weight":null},{"id":"hose","name":"Hose","category":"Clothing","cost":"2 gp","weight":null},{"id":"knife_sheath","name":"Knife sheath","category":"Clothing","cost":"3 cp","weight":null},{"id":"mittens","name":"Mittens","category":"Clothing","cost":"3 sp","weight":null},{"id":"pin","name":"Pin","category":"Clothing","cost":"6 gp","weight":null},{"id":"plain_brooch","name":"Plain brooch","category":"Clothing","cost":"10 gp","weight":null},{"id":"robe_common","name":"Robe, Common","category":"Clothing","cost":"9 sp","weight":null},{"id":"robe_embroidered","name":"Robe, Embroidered","category":"Clothing","cost":"20 gp","weight":null},{"id":"sandals","name":"Sandals","category":"Clothing","cost":"5 cp","weight":null},{"id":"sash","name":"Sash","category":"Clothing","cost":"2 sp","weight":null},{"id":"shoes","name":"Shoes","category":"Clothing","cost":"1 gp","weight":null},{"id":"silk_jacket","name":"Silk jacket","category":"Clothing","cost":"80 gp","weight":null},{"id":"surcoat","name":"Surcoat","category":"Clothing","cost":"6 sp","weight":null},{"id":"sword_scabbard_hanger_baldric","name":"Sword scabbard, hanger,
